name: wizh_test
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  easy_debounce: ^2.0.3
  iconsax_plus: ^1.0.0
  pull_to_refresh: ^2.0.0
  flutter_widget_from_html: ^0.16.0
  webview_flutter: ^4.10.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.8.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/