import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_GB': {
          'splash_description': 'Find job for disability',
          'onboard_title_first': 'Find perfect job vacancy',
          'onboard_desc_first': 'Find perfect job vacancy for special person like you',
          'onboard_title_second': 'Chat with our Consultant',
          'onboard_desc_second': 'Our consultant will give you best recommendation',
          'onboard_title_third': 'Do your assesment task',
          'onboard_desc_third': 'Do our assesment and find out your score',
          'next': 'Next',
          'skip': 'Skip',
          'email': 'Email',
          'password': 'Password',
          'login': 'Login',
          'welcome_to_jobdis': 'Welcome to Jobdis!',
          'enter_login_account': 'Enter your account to login',
          'dont_have_an_account': "Don't have an account",
          'register': "Register",
          'search_job': 'Search Job',
          'search_consultation': 'Search Consultation Session',
          'job_available': 'Jobs avaliable for you',
          'session_available': 'Chat session available',
          'fulltime': 'Full Time',
          'parttime': 'Part Time',
          'freelance': 'Freelance',
          'internship': 'Internship',
          'quick_apply': "Quick Apply",
          'posted_at': "Posted at",
          'password_confirmation': 'Password Confirmation',
          'consultant': 'Consultant',
          'online': 'Online',
          'busy': 'Busy',
          'offline': 'Offline',
          'success': 'Success',
          'success_reserved_session': 'You\'ve successfully reserved this chat session',
          'pending': 'Pending',
          'hold_reserved_session': 'Hold up we\'re still verificating your payment',
          'paid': 'Paid',
          'name': 'Name',
          'date': 'Date',
          'price': 'Price',
          'status': 'Status',
          'start_chat_session': 'Start Chat Session',
          'no_pay_session': 'Look like you dont have payment with this session',
          'no_pay_feature': 'Look like you dont have payment with this feature',
          'pay_session': 'Pay Chat Session',
          'how_to_pay': 'How to Pay',
          'payment_proof': 'Payment Proof',
          'account_successfully_copied': 'Account number successfully copied',
          'pay_now': 'Pay Now',
          'type_something': 'Type something...',
          'are_you_sure': 'Are you sure?',
          'confirm_out': 'When you leave, the consultation session will end. Are you sure?',
          'no_data': 'Data not found',
          'no_data_job': 'No Job available right now',
          'no_data_consultation': 'No Consultation session available right now',
          'profile': 'Profile',
          'change_password': 'Change Password',
          'change_language': 'Change Language',
          'logout': 'Logout',
          'save': 'Save',
          'pay_feature': 'Pay Feature',
          'start_test': 'Start Test',
          'feature': 'Feature',
          'full_name': 'Full Name',
          'setting': 'Setting',
          'easy_apply': 'Easy Apply',
          'session_busy': 'Session is busy you have to wait before start this chat session',
          'know_personality': 'Start test and know your personality',
          'payment_instruction':
              '<ol style="list-style-position: inside; padding-left: 8px; margin-left: 8px;"><li><strong>Log in</strong> to your banking service (whether through an app, online, or ATM).</li><li><strong>Select</strong> the option for <strong>Transfer</strong> or <strong>Money Transfer</strong>.</li><li><strong>Enter</strong> the destination BNI account number and recipient\'s name.</li><li><strong>Fill in</strong> the amount of money to be transferred.</li><li><strong>Confirm</strong> all the data you have entered.</li><li><strong>Follow</strong> the instructions to complete the transfer, including entering the OTP if required.</li><li><strong>Done!</strong> Wait for a notification that the transfer was successful.</li></ol>',
          'choose_question': 'Choose the most suitable statement for you below',
          'personality_result': 'Here your personality test result',
          'result_description': 'MBTI personality type can provide insights into your strengths, preferences, and communication style, it shouldn\'t be the sole determinant in job selection. However, knowing your MBTI type can help you better understand roles where you might thrive based on your natural tendencies.',
          'consultation_session_price': 'Consultation Session Price',
          'consultation_session_status': 'Consultation Session Status',
          'manage_session': 'Manage your consultation session here',
          'register_completed': 'Register completed you can login to your account securely',
          'start_register': 'Start to create your Account',
          'register_account': 'Register your account',
          'mbti_test': 'MBTI Test',
          'interest_test': 'Interest Test',
        },
        'id_ID': {
          'interest_test': 'Tes Minat',
          'mbti_test': 'Tes MBTI',
          'start_register': 'Mulai membuat akunmu',
          'register_account': 'Daftarkan akunmu',
          'register_completed': 'Pendaftaran berhasil kamu bisa login ke akunmu dengan aman',
          'manage_session': 'Kelola sesi konsultasi kamu disini',
          'consultation_session_status': 'Status Sesi Konsultasi',
          'consultation_session_price': 'Harga Sesi Konsultasi',
          'splash_description': 'Cari kerja untuk disabilitas',
          'onboard_title_first': 'Cari lowongan sempurna',
          'onboard_desc_first': 'Cari loker sempurna untuk seseorang spesial sepertimu',
          'onboard_title_second': 'Chat dengan konsultan',
          'onboard_desc_second': 'Konsultan kami akan memberikan rekomendasi',
          'onboard_title_third': 'Kerjakan tugas assesmentmu',
          'onboard_desc_third': 'Kerjakan assesment tersedia dan cari tau skormu',
          'next': 'Selanjutnya',
          'skip': 'Lewati',
          'email': 'Surel',
          'password': 'Kata Sandi',
          'password_confirmation': 'Konfirmasi Kata Sandi',
          'login': 'Masuk',
          'welcome_to_jobdis': 'Selamat datang di Jobdis!',
          'enter_login_account': 'Masukkan akunmu untuk login',
          'dont_have_an_account': "Belum punya akun",
          'register': "Daftar",
          'search_job': "Cari Pekerjaan",
          'search_consultation': 'Cari Sesi Konsultasi',
          'job_available': 'Lowongan kerja tersedia',
          'session_available': 'Sesi chat tersedia',
          'fulltime': 'Penuh Waktu',
          'parttime': 'Paruh Waktu',
          'freelance': 'Pekerja Lepas',
          'internship': 'Magang',
          'quick_apply': "Lamar Cepat",
          'posted_at': "Diposting pada",
          'consultant': 'Konsultan',
          'online': 'Online',
          'busy': 'Sibuk',
          'offline': 'Offline',
          'success': 'Berhasil',
          'success_reserved_session': 'Kamu telah berhasil memesan sesi chat ini',
          'pending': 'Ditunda',
          'hold_reserved_session': 'Tunggu kami sedang memverifikasi pembayaranmu',
          'paid': 'Lunas',
          'name': 'Nama',
          'date': 'Tanggal',
          'price': 'Harga',
          'status': 'Status',
          'start_chat_session': 'Mulai Sesi Chat',
          'no_pay_session': 'Kelihatannya kamu belum ada pembayaran di sesi ini',
          'no_pay_feature': 'Kelihatannya kamu belum ada pembayaran di fitur ini',
          'pay_session': 'Bayar Sesi Chat',
          'how_to_pay': 'Cara Pembayaran',
          'payment_proof': 'Bukti Pembayaran',
          'account_successfully_copied': 'Nomor rekening berhasil disalin',
          'payment_now': 'Bayar Sekarang',
          'type_something': 'Ketik sesuatu...',
          'confirm_out': 'Ketika kamu keluar, sesi konsultasi akan diakhiri. Apakah kamu yakin?',
          'are_you_sure': 'Apakah kamu yakin?',
          'no_data': 'Data tidak ditemukan',
          'no_data_job': 'Tidak ada lowongan kerja yang tersedia saat ini',
          'no_data_consultation': 'Tidak ada sesi konsultasi yang tersedia saat ini',
          'profile': 'Profil',
          'change_password': 'Ubah Kata Sandi',
          'change_language': 'Ubah Bahasa',
          'logout': 'Keluar',
          'save': 'Simpan',
          'pay_feature': 'Bayar Fitur',
          'start_test': 'Mulai Tes',
          'feature': 'Fitur',
          'easy_apply': 'Lamar Cepat',
          'full_name': 'Nama Lengkap',
          'pay_now': 'Bayar Sekarang',
          'setting': 'Pengaturan',
          'know_personality': 'Mulai test dan ketahui kepribadianmu',
          'session_busy': 'Sesi sedang sibuk kamu harus menunggu sebelum memulai sesi chat ini',
          'payment_instruction':
              '<ol style="list-style-position: inside; padding-left: 8px; margin-left: 8px;"><li><strong>Login</strong> ke layanan perbankan Anda (apakah itu melalui aplikasi, internet, atau ATM).</li><li><strong>Pilih</strong> opsi untuk <strong>Transfer</strong> atau <strong>Pengiriman Uang</strong>.</li><li><strong>Masukkan</strong> nomor rekening BNI tujuan dan nama penerima.</li><li><strong>Isi</strong> jumlah uang yang akan ditransfer.</li><li><strong>Konfirmasi</strong> semua data yang telah Anda masukkan.</li><li><strong>Ikuti</strong> instruksi untuk menyelesaikan transfer, termasuk memasukkan kode OTP jika diperlukan.</li><li><strong>Selesai!</strong> Tunggu notifikasi bahwa transfer berhasil.</li></ol>',
          'choose_question': 'Pilih pernyataan yang paling sesuai untukmu dibawah ini',
          'personality_result': 'Inilah hasil tes kepribadianmu',
          'result_description': 'Tipe kepribadian MBTI dapat memberikan wawasan tentang kekuatan Anda, preferensi, dan gaya komunikasi, itu tidak boleh menjadi penentu tunggal dalam pemilihan pekerjaan. Namun, mengetahui tipe MBTI Anda dapat membantu Anda lebih memahami peran di mana Anda mungkin berkembang berdasarkan kecenderungan alami Anda.'
        }
      };
}
